import Image from "next/image";

export default function Hiking() {
    return (
        <main className="mx-14">
        <div >
            <div >
                <h1 className="text-5xl text-bold ml-4 text-white my-8">BLUE RIDGE MOUNTAINS</h1>
                <p className="my-5 text-xl text-gray-400 ">Stretching across the eastern United States, the Blue Ridge Mountains&apos; natural beauty characterizes the region, coupled with its rich wildlife. These ancient mountains are famous for their distinctive blue appearance, caused by the release of volatile organic compounds from the forests that blanket the landscape. Exploring the Blue Ridge Mountains offers a wide range of outdoor activities, including hiking, camping, fishing, and wildlife viewing. The region&apos;s forests and diverse ecosystems provide a haven for countless plant and animal species, making it a paradise for nature lovers. </p>
                <p className="my-5 text-xl text-gray-400">Fun fact! The Appalachian Mountains, home to the Blue Ridge Mountains, is one of the oldest mountain chains in the world! The Scottish Highlands are part of the same mountain range, and there is a split in the mountain chain at a trench in the Atlantic Ocean, which moves the mountains further northeast of the trench. You can find canyons in the Blue Ridge Mountains older than any in the Western US, due to the age of the range. </p>
                <h2 className="text-bold text-3xl text-white my-8 ml-4">THE BLUE RIDGE PARKWAY </h2>
                <p className="my-5 text-xl text-gray-400">The Blue Ridge Parkway is a scenic road that winds its way through the heart of the Blue Ridge Mountains. Often hailed as &quot;America&apos;s Favorite Drive,&quot; this iconic route spans 469 miles, connecting Shenandoah National Park in Virginia to Great Smoky Mountains National Park in North Carolina and Tennessee. Driving along the Blue Ridge Parkway is a captivating experience, offering views of the surrounding mountains, valleys, and forests. The parkway is dotted with numerous overlooks, each providing a perspective of the diverse landscapes. As you journey along this scenic route, you&apos;ll have the opportunity to explore charming communities, visit historical sites, and explore outdoor recreational activities. </p>
                <p className="my-5 text-xl text-gray-400">The Blue Ridge Parkway winds through and by several towns in North Carolina and Virginia. The Parkway passes just outside of Asheville, North Carolina. This makes Asheville the ideal city to access the Parkway, as well as the Smoky and Blue Ridge Mountains. There are amazing National Monuments and small towns that scattered along the Parkway in the Asheville area. Asheville, North Carolina has become a popular travel destination and should definitely be added to your list. </p>
                <Image src="/images/hills.jpg" className="my-10 w-auto h-auto" alt="hills"  />
            </div>
            <div className="mt-10">
                <h1 className="text-5xl text-bold text-white ml-4 my-8">SHENANDOAH NATIONAL PARK</h1>
                <p className="my-5 text-xl text-gray-400">Situated in the northern region of the Blue Ridge Mountains, Shenandoah National Park acts as a starting or end point for the Blue Ridge Parkway. Encompassing over 200,000 acres, this pristine wilderness offers a haven of natural beauty. The park boasts panoramic vistas, cascading waterfalls, and an abundance of wildlife. A highlight of Shenandoah National Park is the famous Skyline Drive, a scenic road that traverses the length of the park. Along this route, you can find numerous overlooks, hiking trails, and picnic areas.. Whether you prefer a leisurely drive or an adventurous hike, Shenandoah National Park offers something for everyone. </p>
                <Image alt="park" src="/images/park.jpg" className="my-10 w-auto h-auto"/>
                <h2 className="text-bold text-white ml-4 my-8 text-3xl">THINGS TO DO IN SHENANDOAH NATIONAL PARK </h2>
                <p className="my-5 text-xl text-gray-400">Shenandoah National Park is a playground for outdoor enthusiasts, offering a multitude of recreational activities. Hikers can explore over 500 miles of trails, ranging from easy strolls to challenging treks. The Appalachian Trail passes through the park, offering hikers an unforgettable experience. For those seeking a different perspective, the park&apos;s rivers are perfect for canoeing, kayaking, or fishing. Visitors can also embark on scenic drives, cycle along the Skyline Drive, or partake in horseback riding amidst the park&apos;s enchanting landscapes. Camping facilities are also available, allowing visitors to experience the park overnight. </p>
                <p className="my-5 text-xl text-gray-400">One of my favorite hikes in Shenandoah is the Old Rag Trail. This hike takes you to the top of a mountain peak, in one of the highest parts of the Blue Ridge Mountains, and offers views of the stretching mountainous landscape. Water pools on the top also attract most of the wildlife you would expect to see in this part of the southeast, namely black bears and deer. Make sure when you are in the park that you hike this strenuous but rewarding trail </p>
                <p className="my-5 text-xl text-gray-400">Beyond its natural wonders, Shenandoah National Park also boasts a rich heritage. Visitors can explore historical sites, including prehistoric Native American archaeological sites and remnants of early European settlements. The park also features rustic cabins and lodges built by the Civilian Conservation Corps in the 1930s. The Byrd Visitor Center provides informative exhibits that delve into the park&apos;s history, ecology, and conservation efforts.</p>
            </div>
        </div>
        </main>
    )
}
